### ISSUE TITLE
علت عدم استفاده از سرویس جنریک برای عملیات کراد؟

### ISSUE THREAD

**Issue by iamhaaamed** [VahidN/AspNetIdentityDependencyInjectionSample#10]
سلام می خواستم بدون چرا در لایه سرویس یک سرویس جنریک برای عملیات کراد ساده نوشته نشده تا همه سرویس ها ازش به ارث برن و دیگه لازم نباشه برای هر سرویس کراد رو پیاده سازی کرد؟ مورد دوم اینکه با توجه به اینکه برگشت دادن اینامریبل در لایه سرویس مشکل آفرین هست به چه صورتی باید متد گت آل رو که نیاز به متد اینکلود داره پیاده سازی کرد؟ آیا به ازای هر گت آل ای که نیاز به اینکلود داره باید یک متد جدا تعریف بشه؟

**Comment by VahidN** [comment]
- [EF 12](http://www.dotnettips.info/post/842/ef-code-first-12)
- [الگوى مخزن آرى يا خير](http://www.dotnettips.info/post/1773/repository-%D9%87%D8%A7-%D8%B1%D9%88%DB%8C-unitofwork-%D8%A7%DB%8C%D8%AF%D9%87-%D8%AE%D9%88%D8%A8%DB%8C-%D9%86%DB%8C%D8%B3%D8%AA%D9%86%D8%AF)

**Comment by iamhaaamed** [comment]
من دقیق متوجه نشدم داخل مطلب گفته شده استفاده از جنریک ریپازیتوری صحیح نیست ولی در انتهای نظرات در مورد سرویس ها این موضوع سرویس جنریک مطرح شده و حتی یه مطلب در موردش قرار داده شده.
در مورد متد اینکلود هم مطلبی توی لینک هایی که فرمودید پیدا نکردم
