### ISSUE TITLE
custom errors

### ISSUE THREAD

**Issue by iamhaaamed** [VahidN/AspNetIdentityDependencyInjectionSample#11]
با سلام 
در صورتی که بخوایم custom error ها رو در این پروژه فعال کنیم برای SEO هم مشکلی ایجاد نشه به چه صورتی عمل بشه بهتر هست؟

**Comment by VahidN** [comment]
اين نوع سؤالات خارج از موضوع پروژه‌ي جاري هستند
[http://www.dotnettips.info/post/820/asp-net-mvc-16](http://www.dotnettips.info/post/820/asp-net-mvc-16)
