### ISSUE TITLE
How to get user profile data inside views?

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/AspNetIdentityDependencyInjectionSample#2]
I want to access user profile information inside my views. for example I have a field called `UserAvatar` So I want to access this property this way:
`User.Identity.GetUserAvatar();`
Any idea?

**Comment by SirwanAfifi** [comment]
I found the solution:
First of all we should create this extension method to get out custom property:

```
public static class IdentityExtention
    {
        public static string GetAvatar(this System.Security.Principal.IIdentity user)
        {
            var service = SmObjectFactory.Container.GetInstance<IApplicationUserManager>();
            return service.FindByIdAsync(int.Parse(user.GetUserId())).Result.Avatar;
        }
    }
```

Then we can use it inside our view this way:
`@User.Identity.GetAvatar()`

**Comment by VahidN** [comment]
If it's for 1 user, that's OK (even it violates the rule of `don't query from the view`). But if it you are using this method in a loop, it will produce `n+1 selects` which could be solved by issuing just one query.
