### ISSUE TITLE
Passing params

### ISSUE THREAD

**Issue by shreniks** [VahidN/AspNetIdentityDependencyInjectionSample#3]
Hey,

Thanks for sharing the code. 

I am a bit new with this and I am trying to pass a connection string parameter to the ApplicationDBContext. Can you please give some tips on that?

**Comment by VahidN** [comment]
Hello,
You can set the connection string in [web.config](https://github.com/VahidN/AspNetIdentityDependencyInjectionSample/blob/master/AspNetIdentityDependencyInjectionSample/Web.config) file 

``` xml
<connectionStrings>
    <clear />
    <add name="connectionString1" connectionString="Data Source=(local);Initial Catalog=TestDbIdentity;Integrated Security = true" providerName="System.Data.SqlClient" />
</connectionStrings>
```

Its key (`connectionString1`) is set in the [ApplicationDbContext.cs](https://github.com/VahidN/AspNetIdentityDependencyInjectionSample/blob/master/AspNetIdentityDependencyInjectionSample.DataLayer/Context/ApplicationDbContext.cs) file

``` csharp
public ApplicationDbContext(): base("connectionString1")
{
```

**Comment by VahidN** [comment]
Aslo if you want to change the connection string at runtime, first you need to add a new constructor to the [ApplicationDbContext.cs](https://github.com/VahidN/AspNetIdentityDependencyInjectionSample/blob/master/AspNetIdentityDependencyInjectionSample.DataLayer/Context/ApplicationDbContext.cs) file

``` csharp
        public ApplicationDbContext(string connectionString)
            : base(connectionString)
        {
            //Note: defaultConnectionFactory in the web.config file should be set.
        }
```

And then in the [SmObjectFactory.cs](https://github.com/VahidN/AspNetIdentityDependencyInjectionSample/blob/master/AspNetIdentityDependencyInjectionSample.IocConfig/SmObjectFactory.cs) file, set the connection string:

``` csharp
 ioc.For<IUnitOfWork>()
      .HybridHttpOrThreadLocalScoped()
      .Use<ApplicationDbContext>()
      // Remove these 2 lines if you want to use a connection string named connectionString1, defined in the web.config file.
       .Ctor<string>("connectionString")
       .Is("Data Source=(local);Initial Catalog=TestDbIdentity;Integrated Security = true");
```

**Comment by shreniks** [comment]
Cheers mate. Will give that a go.

**Comment by shrenicshah** [comment]
Hey just one last question. 

You have commented out this line in the SmObjectFactory. 

//config.For<IDataProtectionProvider>().Use(()=> app.GetDataProtectionProvider()); // In Startup class

Is there a way I can inject the IDataProtectionProvider in the SmObjectFactory and not in the Startup class?
