### ISSUE TITLE
Business Transaction?

### ISSUE THREAD

**Issue by MinaSaz** [VahidN/AspNetIdentityDependencyInjectionSample#8]
hi !

I'm new in both Asp.net Identity and DI and have some problem understanding the code.

my question is that where the changes are persisted to database , where we call SaveAllChanges?
where is business transaction boundary?

**Comment by VahidN** [comment]
Hi, 
You need to study `Context Per Request` and `Unit of work` patterns. [More info here](http://www.dotnettips.info/post/842/ef-code-first-12) and also [here](http://www.dotnettips.info/post/1937/%d8%a7%d8%b9%d9%85%d8%a7%d9%84-%d8%aa%d8%b2%d8%b1%db%8c%d9%82-%d9%88%d8%a7%d8%a8%d8%b3%d8%aa%da%af%db%8c%e2%80%8c%d9%87%d8%a7-%d8%a8%d9%87-%d9%85%d8%ab%d8%a7%d9%84-%d8%b1%d8%b3%d9%85%db%8c-asp-net-identity).
