### ISSUE TITLE
Problem with changing password when using AngularJS

### ISSUE THREAD

**Issue by skhalil89** [VahidN/AspNetIdentityDependencyInjectionSample#9]
Sallam,
I'm using this code https://github.com/tjoudeh/AngularJSAuthentication and yours. every projects work nice seprately but when i using them in single project, the problem of changing password appears. means that using ApplicationManager in service layer and OAuthentication with AngularJS in UI layer make some wrong things that some of operations do not work . Like changing password or recovery or other things about authority and authentication even like change other filed of ApplicationUser. 
So  still could not undrastand.
can you help me, please?

**Comment by sedreza** [comment]
The sample i did make.

**Comment by skhalil89** [comment]
some code that i can show: 
the ConfigureOAuth method in Startup class:

```

 public void ConfigureOAuth(IAppBuilder app)
        {

            //use a cookie to temporarily store information about a user logging in with a third party login provider
            app.UseExternalSignInCookie(Microsoft.AspNet.Identity.DefaultAuthenticationTypes.ExternalCookie);
            OAuthBearerOptions = new OAuthBearerAuthenticationOptions();

            OAuthAuthorizationServerOptions OAuthServerOptions = new OAuthAuthorizationServerOptions()
            {

                AllowInsecureHttp = true,
                TokenEndpointPath = new PathString("/token"),
                AccessTokenExpireTimeSpan = TimeSpan.FromMinutes(30),
                Provider = new SimpleAuthorizationServerProvider(),
                RefreshTokenProvider = new SimpleRefreshTokenProvider()
            };

            // Token Generation
            app.UseOAuthAuthorizationServer(OAuthServerOptions);
            app.UseOAuthBearerAuthentication(OAuthBearerOptions);


        }
```

I can not upload code here, so: http://s000.tinyupload.com/index.php?file_id=61995706542396062196
